apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: grafana-alerting
  namespace: grafana
spec:
  tags:
    app: grafana-alerting
    component: slack-webhooks
