apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-datasource-secret-store
  namespace: grafana
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://grafana-grafana-b607eb82.vault.azure.net/
      serviceAccountRef:
        name: grafana-alerting
