apiVersion: vault.dis.altinn.cloud/v1alpha1
kind: Vault
metadata:
  name: grafana-alerting
  namespace: grafana
spec:
  identityRef:
    name: grafana-alerting
  externalSecrets: true
  sku: standard
  tags:
    app: grafana-alerting
    component: slack-webhooks
