{
 "title": "Envoy Global",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [ "Data Plane" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(cluster_upstream_rq_time_bucket,k8s_namespace_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(server_live)" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(k8s_pod_name) (server_uptime{k8s_namespace_name=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (server_memory_heap_size{k8s_namespace_name=~\"$Namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (server_memory_allocated{k8s_namespace_name=~\"$Namespace\"})"
    }
   ]
  },
  { "title": "DownStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Downstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_downstream_rq_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "Envoy HTTP Downstream Rq total"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(http_downstream_cx_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_downstream_rq_time_bucket{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval])))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_downstream_rq_time_bucket{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval])))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_downstream_rq_time_bucket{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval])))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (listener_downstream_cx_active{k8s_namespace_name=~\"$Namespace\"})",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "TCP Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(tcp_downstream_cx_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "TCP Downstream Bytes Rx/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(tcp_downstream_cx_rx_bytes_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "TCP Downstream Bytes Tx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(tcp_downstream_cx_tx_bytes_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Upstream RPS",
   "type": "timeseries",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(cluster_upstream_rq_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_upstream_cx_total{k8s_namespace_name=~\"$Namespace\",}[$__rate_interval])) by (k8s_namespace_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cluster_upstream_rq_time_bucket{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval])) by (le, k8s_namespace_name))",
     "legendFormat": "{{k8s_namespace_name}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(cluster_upstream_rq_time_bucket{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval])) by (le, k8s_namespace_name))",
     "legendFormat": "{{k8s_namespace_name}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cluster_upstream_rq_time_bucket{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval])) by (le, k8s_namespace_name))",
     "legendFormat": "{{k8s_namespace_name}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cluster_upstream_cx_active{k8s_namespace_name=~\"$Namespace\"}) by (k8s_namespace_name)",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "Upstream Bytes Rx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(cluster_upstream_cx_rx_bytes_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "Upstream Bytes Tx/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (rate(cluster_upstream_cx_tx_bytes_total{k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  { "title": "Upstream Response Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Upstream 2xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_upstream_rq_xx_total{envoy_response_code_class=~\"2\",k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_upstream_rq_xx_total{envoy_response_code_class=~\"3\",k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_upstream_rq_xx_total{envoy_response_code_class=\"4\",k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_upstream_rq_xx_total{envoy_response_code_class=\"5\",k8s_namespace_name=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Endpoint Percentage Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(cluster_membership_healthy{k8s_namespace_name=~\"$Namespace\"}) by (k8s_namespace_name) / avg(cluster_membership_total{k8s_namespace_name=~\"$Namespace\"}) by (k8s_namespace_name)",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (cluster_membership_total{k8s_namespace_name=~\"$Namespace\"})",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (cluster_membership_healthy{k8s_namespace_name=~\"$Namespace\"})",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (cluster_membership_total{k8s_namespace_name=~\"$Namespace\"}) - sum by(k8s_namespace_name) (cluster_membership_healthy{k8s_namespace_name=~\"$Namespace\"})",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  },
  { "title": "TLS Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "TLS Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by (envoy_tls_certificate) ((listener_ssl_certificate_expiration_unix_time_seconds{k8s_namespace_name=~\"$Namespace\"} - time()) / 86400)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}