apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboards
  - products/dialogporten/alerting
  - products/infoportal/alerting
  - products/infoportal/dashboards
  - products/ki-norge/alerting
  - products/ki-norge/dashboards
  - platform/secrets
