apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-prometheus-auth
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-alerting-secret-store
    kind: SecretStore
  target:
    name: example-prometheus-auth
    creationPolicy: Owner
  data:
    - secretKey: authorization
      remoteRef:
        key: datasource-example-prometheus-authorization
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-tempo-auth
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-alerting-secret-store
    kind: SecretStore
  target:
    name: example-tempo-auth
    creationPolicy: Owner
  data:
    - secretKey: authorization
      remoteRef:
        key: datasource-example-tempo-authorization
