apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: example-prometheus
  namespace: grafana
spec:
  uid: example-prometheus
  instanceSelector:
    matchLabels:
      dashboards: external-grafana
  datasource:
    name: Example Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus.example.invalid
    isDefault: false
    editable: false
    jsonData:
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: "${authorization}"
  valuesFrom:
    - targetPath: secureJsonData.httpHeaderValue1
      valueFrom:
        secretKeyRef:
          name: example-prometheus-auth
          key: authorization
