apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: altinn-studio-metrics-auth
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-alerting-secret-store
    kind: SecretStore
  target:
    name: altinn-studio-metrics-auth
    creationPolicy: Owner
  data:
    - secretKey: authorization
      remoteRef:
        key: datasource-altinn-studio-authorization
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: altinn-studio-traces-auth
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-alerting-secret-store
    kind: SecretStore
  target:
    name: altinn-studio-traces-auth
    creationPolicy: Owner
  data:
    - secretKey: authorization
      remoteRef:
        key: datasource-altinn-studio-authorization
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: altinn-studio-logs-auth
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-alerting-secret-store
    kind: SecretStore
  target:
    name: altinn-studio-logs-auth
    creationPolicy: Owner
  data:
    - secretKey: authorization
      remoteRef:
        key: datasource-altinn-studio-authorization
