apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: external-grafana-infoportal
  namespace: grafana
spec:
  title: Infoportal
  instanceSelector:
    matchLabels:
      dashboards: external-grafana
